# Generated by Django 4.2.5 on 2023-09-21 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_rename_post_id_comment_post_id_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='post_detail', to=settings.AUTH_USER_MODEL),
        ),
    ]
